version: '3'

volumes:
  event_service_postgres_data: {}
  event_service_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: event_service_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: event_service_production_postgres
    volumes:
      - event_service_postgres_data:/var/lib/postgresql/data
      - event_service_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  vue:
    build:
      context: .
      dockerfile: ./compose/local/vue/Dockerfile
    volumes:
      - ./vue:/app
    depends_on:
      - django
    ports:
      - 5000:8080

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: event_service_local_celeryworker
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: event_service_local_celerybeat
    depends_on:
      - redis
      - postgres
      
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: event_service_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
